document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head> ");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' /> ");
document.writeln("<meta http-equiv=\'Content-Language\' content=\'zh-CN\' /> ");
document.writeln("<title>Hello World</title> ");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<?php");
document.writeln("/*图片防盗链处理代码*/");
document.writeln("error_reporting(0);");
document.writeln("header(\'Content-Type:image/jpeg\');");
document.writeln("$picurl = $_GET[\'pic\'];");
document.writeln("echo npimgcurl($picurl);");
document.writeln("function npimgcurl($url){");
document.writeln("	$ch=curl_init();");
document.writeln("	curl_setopt($ch, CURLOPT_URL, $url);");
document.writeln("	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); // 对认证证书来源的检查");
document.writeln("	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE); // 从证书中检查SSL加密算法是	");
document.writeln("	curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);");
document.writeln("	$data=curl_exec($ch);");
document.writeln("	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT,5);");
document.writeln("	curl_setopt($ch,CURLOPT_REFERER,$url);	");
document.writeln("	curl_close($ch);");
document.writeln("	return $data;");
document.writeln("}");
document.writeln("?>");
document.writeln("</body>");
document.writeln("</html> ");
